apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portainer 
  namespace: portainer 
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portainer.baozitao.com`) 
      kind: Rule
      services:
        - kind: Service 
          name: portainer 
          namespace: portainer 
          port: 9000

