apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: kubebaojt 
spec:
  hosts:
  - {name: node1,  address: 10.0.0.107, internalAddress: 10.0.0.107, password: "99131456", privateKeyPath: "/root/.ssh/baojt.pem"}
  - {name: node2,  address: 10.0.0.201, internalAddress: 10.0.0.201, password: "99131456", privateKeyPath: "/root/.ssh/baojt.pem"}
  - {name: node3,  address: 10.0.0.149, internalAddress: 10.0.0.149, password: "99131456", privateKeyPath: "/root/.ssh/baojt.pem"}
  roleGroups:
    etcd:
    - node1
    master: 
    - node1 
    worker:
    - node1 
    - node2
    - node3
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    #internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: kubebaojt
  network:
    plugin: flannel 
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    # multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    enableMultusCNI: false
  registry:
    registryMirrors: ["http://10.0.0.231:8083"]
    insecureRegistries: ["10.0.0.231:8083"]
    privateRegistry: 10.0.0.231:8083
  addons: []


