apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: kubebaojt 
spec:
  hosts:
  - {name: master, address: 16.163.16.70, internalAddress: 172.31.32.153, privateKeyPath: "/root/.ssh/baojt.pem", arch: arm64}
  - {name: node1, address: 16.163.170.211, internalAddress: 172.31.32.185, privateKeyPath: "/root/.ssh/baojt.pem", arch: arm64}
  - {name: node2, address: 18.166.96.138, internalAddress: 172.31.37.142, privateKeyPath: "/root/.ssh/baojt.pem", arch: arm64}
  roleGroups:
    etcd:
    - master
    master: 
    - master 
    worker:
    - node1 
    - node2
  controlPlaneEndpoint:
    ##Internal loadbalancer for apiservers 
    #internalLoadbalancer: haproxy
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.21.5
    clusterName: cluster.local
  network:
    plugin: flannel 
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    # multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    enableMultusCNI: false
  registry:
    registryMirrors: ["http://help.baozitao.cn:8083"]
    insecureRegistries: ["help.baozitao.cn:8083"]
  addons: []


